[package]
name = "core-bench"
version = "0.6.10"
edition = "2021"
license = "Apache-2.0"
publish = false
autolib = false

[dependencies]
core-api = { package = "mushroomdb", path = "../core-api" }
core-storage = { package = "mushroomdb-storage", path = "../core-storage" }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "engine"
harness = false
