#!/usr/bin/env bash
# gen-llms-full.sh — regenerates llms-full.txt at the repo root.
# Run from any directory; the script locates the repo root via git.
# Output: <repo-root>/llms-full.txt
#
# Generator: scripts/gen-llms-full.sh (mushroomdb repo)
# To regenerate: bash scripts/gen-llms-full.sh

set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
OUT="$REPO_ROOT/llms-full.txt"

SITE_DIR="$REPO_ROOT/docs/site"
README="$REPO_ROOT/README.md"

# Ordered list of site docs — index first, then feature docs, then reference
SITE_DOCS=(
    index.md
    quickstart.md
    code-graph.md
    concurrency.md
    multiprocess.md
    rules.md
    mcp.md
    association-bench.md
    query.md
    api.md
    subscriptions.md
    timetravel.md
    views.md
    fulltext.md
    algorithms.md
    masks.md
    service.md
    suggest.md
    testing.md
)

# Strip raw HTML tags, keeping every other angle-bracket token intact.
#
# A blanket `s/<[^>]*>//g` cannot be used here: the sources are full of tokens
# that look like tags and are not. CLI placeholders (`<db-dir>`, `<path>`,
# `<dest>`), Rust generics (`Vec<String>`, `Option<f64>`), the GraphML `<data>`
# element, and the map digest's literal `<mixed>` cluster label would all be
# deleted silently, corrupting pasted command lines and real tool output.
#
# So only a known list of HTML tag names is stripped. Three of those names
# collide with real content — `mushroomdb why <db> <a> <b>` writes `<a>` and
# `<b>` bare — so those are stripped only in a form markup actually takes: a
# closing tag, or an opening tag carrying an attribute.
HTML_BLOCK_TAGS='img|br|hr|p|div|details|summary|picture|source|figure|figcaption|h[1-6]'
HTML_AMBIGUOUS_TAGS='a|b|i|em|strong|span|code|sub|sup'

strip_html() {
    sed -E \
        -e "s@</($HTML_BLOCK_TAGS|$HTML_AMBIGUOUS_TAGS)>@@g" \
        -e "s@<($HTML_BLOCK_TAGS|$HTML_AMBIGUOUS_TAGS)[[:space:]][^>]*>@@g" \
        -e "s@<($HTML_BLOCK_TAGS)[[:space:]]*/?>@@g" \
        "$1"
}

{
    echo "# mushroomdb — full LLM reference"
    echo "# Generated by scripts/gen-llms-full.sh (mushroomdb repo)"
    echo "# Source: README.md + docs/site/*.md"
    echo "# This file is tracked; regenerate and commit with: bash scripts/gen-llms-full.sh"
    echo ""
    echo "---"
    echo ""

    echo "## README"
    echo ""
    # Strip raw HTML tags; keep text, code blocks and literal <angle> tokens
    strip_html "$README"
    echo ""
    echo "---"
    echo ""

    for doc in "${SITE_DOCS[@]}"; do
        path="$SITE_DIR/$doc"
        if [[ -f "$path" ]]; then
            echo "## docs/site/$doc"
            echo ""
            # Same rules as the README above
            strip_html "$path"
            echo ""
            echo "---"
            echo ""
        fi
    done
} > "$OUT"

SIZE=$(wc -c < "$OUT")
LINES=$(wc -l < "$OUT")

echo "Generated: $OUT"
echo "  size:  $SIZE bytes"
echo "  lines: $LINES"
