[package]
name = "mushroomdb-query"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Cypher query planner and executor for mushroomdb"

[lib]
name = "core_query"

[dependencies]
core-storage = { package = "mushroomdb-storage", path = "../core-storage", version = "0.6.10" }

[dev-dependencies]
proptest = { workspace = true }
